weather_list = [
    "weather",
    "forecast",
    "temperature",
    "rain",
    "raining",
    "rainy",
    "sunny",
    "cloudy",
    "clouds",
    "storm",
    "stormy",
    "thunder",
    "thunderstorm",
    "snow",
    "snowing",
    "snowy",
    "humidity",
    "wind",
    "windy",
    "heat",
    "hot",
    "cold",
    "chilly",
    "freeze",
    "freezing",
    "drizzle",
    "mist",
    "fog",
    "foggy",
    "hail",
    "showers",
    "UV index",
    "dew point",
    "barometer",
    "pressure",
    "climate",
    "weather report",
    "weather update",
    "weather today",
    "weather tomorrow",
    "weekend weather",
    "daily forecast",
    "weekly forecast",
    "weather conditions",
    "air quality",
    "temperature outside",
]
search_prefixes = [
    "search for",
    "search google for",
    "search google",
    "search",
    "can you search for",
    "could you search for",
    "please search for",
    "i want to search for",
    "i want to search",
    "find information on",
    "look up",
    "look up on google",
    "google",
    "google search",
    "can you google",
    "show me",
    "show me results for",
    "what is",
    "who is",
]
todo_list = []
